create structure
Studio-Yandex-Practicum/rehabilitation_bot pull request #1
Opened 2023-04-18 10:30 UTC by SolovyevAlexey

2023-04-18 13:50 UTC, Yana-Denisova requested changes
Привет, давай добавим .vscode в гитигнор и удалим папку и репозитория.

2023-04-18 13:50 UTC, JM1k1 requested changes

2023-04-18 13:50 UTC, JM1k1 commented on .vscode/settings.json
> +}
Не заполнил gitignore? 
Папка с конфигами не должна улетать в пуш.

2023-04-18 13:50 UTC, JM1k1 commented on requirements.txt
> +pre-commit==3.2.2; python_version == "3.11"
Необходимо убрать все дочерние зависимости!

2023-04-18 13:50 UTC, JM1k1 commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
Нет пустой строки на конце файла. 
[No newline at end of file (W292) - Flake8 Rules](https://www.flake8rules.com/rules/W292.html)

2023-04-18 13:50 UTC, JM1k1 commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
Необходимо добавить локальные хуки (flak8, isort)
А также заполнить `setup.cfg` для flake8
```suggestion
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: local
  hooks:

    - id: isort
      name: isort
      entry: isort
      files: ^(bot/|core/|src/)
      language: system
      types: [python]
      args: ["--profile", "black", --line-length=79]

    - id: flake8
      name: flake8
      entry: flake8
      files: ^(bot/|core/|src/)
      language: system
      types: [python]
      args: [--config, setup.cfg]

```

2023-04-19 15:00 UTC, JM1k1 requested changes

2023-04-19 16:53 UTC, Yana-Denisova approved these changes

2023-04-19 22:11 UTC, merged