main_handler
Studio-Yandex-Practicum/rehabilitation_bot pull request #10
Opened 2023-05-08 14:36 UTC by SolovyevAlexey

2023-05-10 10:40 UTC, JM1k1 requested changes

2023-05-10 10:40 UTC, JM1k1 commented on src/bot/conversations/main_application.py
> +MAIN_MENU = range(1)
Давай перенесем это в файл state.py
```suggestion
(
    MAIN_MENU,
    BACK
) = range(2)
```

2023-05-10 10:40 UTC, JM1k1 commented on src/application.py
> +    )
Перенеси хэндлер в handlers.py

2023-05-10 10:42 UTC, Yana-Denisova requested changes

2023-05-10 10:42 UTC, Yana-Denisova commented on src/application.py
> +    main_handler = ConversationHandler(
Давай этот хендлер будем просто импортировать из handlers.py вместо CommandHandler("start", start)

2023-05-11 12:42 UTC, JM1k1 requested changes

2023-05-11 12:42 UTC, JM1k1 commented on src/application.py
> +from telegram.ext import (Application)
```suggestion
from telegram.ext import Application
```

2023-05-11 12:42 UTC, JM1k1 commented on src/bot/conversations/main_application.py
> +async def main_menu(update: Update):
```suggestion
async def main_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
```

2023-05-11 12:42 UTC, JM1k1 commented on src/bot/conversations/main_application.py
> +async def main_menu(update: Update):
```suggestion
async def main_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show the main menu to the user and set the bot's commands."""
```

2023-05-12 16:46 UTC, JM1k1 requested changes

2023-05-12 16:46 UTC, JM1k1 commented on src/bot/handlers.py
> +    )
```suggestion
from telegram.ext import (CallbackQueryHandler, CommandHandler,
                          ConversationHandler)

from bot.constants.state import MAIN_MENU
from bot.conversations.main_application import main_menu, start

main_handler = ConversationHandler(
    entry_points=[
        CommandHandler('start', start),
    ],
    states={
        MAIN_MENU: [
            CallbackQueryHandler(
                # menu_application.menu, pattern=fr"^{key.MENU}_\S*$"
            ),
        ],
    },
    fallbacks=[
        CommandHandler('menu', main_menu)
    ],
    allow_reentry=True,
)

```

2023-05-14 20:21 UTC, Yana-Denisova approved these changes

2023-05-15 12:47 UTC, merged