Feature12/menu constants
Studio-Yandex-Practicum/rehabilitation_bot pull request #12
Opened 2023-05-13 15:20 UTC by nikitairl

Первый пул реквест, надеюсь все правильно запулил. :)

Добавил константы для меню.
Для удобства добавил необходимые, как мне кажется, модели и константу специальностей.
Вопросы для меню взял из фич-листа.

2023-05-15 13:15 UTC, Yana-Denisova requested changes

2023-05-15 13:15 UTC, Yana-Denisova commented on src/bot/constants/models.py
> +class BaseFormModel(BaseModel):
Модель для анкеты уже сделал другой студент в src\bot\core\db\schemas.py , давай туда добавим твою регулярку в full_name

2023-05-15 13:28 UTC, JM1k1 requested changes

2023-05-15 13:28 UTC, JM1k1 commented on src/bot/constants/key.py
> +BUTTON = "BUTTON"
Нет новой строки в конце файла. ([W292](https://www.flake8rules.com/rules/W292.html))
Настрой прекоммит и линтер. :)

2023-05-15 13:28 UTC, JM1k1 commented on src/bot/constants/info/menu.py
> +}
Реализация формы у нас будет через схему и отдельный хэндлер, а константы в этом файле представляют собой лишь меню и под меню. 
Предлагаю созвонится и обсудить этот момент.

2023-05-16 10:12 UTC, Yana-Denisova commented on src/bot/constants/info/menu.py
> +}
Пуллреквесту необходимо давать **информативное** описание и название консистентное проделанным изменениям. 
А так же в описании необходимо указать  **номер** и **название** задачи.

2023-05-16 21:54 UTC, nikitairl commented on src/bot/constants/choices.py
> +SPECIALTY = {
Принято, файл убрал.

2023-05-16 21:54 UTC, nikitairl commented on src/bot/constants/key.py
> +CHOICES = "CHOICES"
Лишнее убрал.

2023-05-16 21:54 UTC, nikitairl commented on src/bot/constants/models.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Перенес.

2023-05-16 21:54 UTC, nikitairl commented on src/bot/constants/models.py
> +class BaseFormModel(BaseModel):
Добавил регулярку в модель дб.

2023-05-16 21:55 UTC, nikitairl commented on src/bot/constants/key.py
> +BUTTON = "BUTTON"
Добавил строку, установил пре-коммит.

2023-05-17 09:40 UTC, Yana-Denisova requested changes

2023-05-17 09:40 UTC, Yana-Denisova commented on src/bot/constants/info/text.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Давай импортируем твою регулярку в src\bot\core\db\schemas.py и будем использовать в full_name

2023-05-17 09:40 UTC, Yana-Denisova commented on src/bot/constants/info/text.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Нет новой строки в конце файла  :)

2023-05-17 09:40 UTC, Yana-Denisova commented on src/bot/constants/key.py
> +CHOICES = "CHOICES"
Давай пока уберем CHOICES :)

2023-05-17 09:40 UTC, Yana-Denisova commented on src/bot/constants/key.py
> +CHOICES = "CHOICES"
Нет новой строки в конце файла :)

2023-05-17 09:40 UTC, Yana-Denisova commented on src/bot/constants/info/main_menu.py
> +}
У тебя сейчас есть два файла menu.py и main_menu.py, давай этот код перенесем в menu.py а main_menu.py удалим.

2023-05-17 13:57 UTC, nikitairl commented on src/bot/constants/info/text.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Импортировал регулярку и указал ее в качестве проверки в модель bd. Сделал это еще после первого предложения так поступить, но видимо что-то пошло не так :)

2023-05-17 13:58 UTC, nikitairl commented on src/bot/constants/key.py
> +CHOICES = "CHOICES"
Сделал.

2023-05-17 13:58 UTC, nikitairl commented on src/bot/constants/info/text.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Привел в должный вид.

2023-05-17 13:58 UTC, nikitairl commented on src/bot/constants/key.py
> +CHOICES = "CHOICES"
Сделал.

2023-05-17 13:58 UTC, nikitairl commented on src/bot/constants/info/main_menu.py
> +}
Сделано.

2023-05-18 11:31 UTC, Yana-Denisova requested changes

2023-05-18 12:08 UTC, nikitairl commented on src/bot/constants/info/text.py
> +FULL_NAME_REGEX = r"^([А-Яа-яЁё\-]+\b {,3}){2,}$"
Справедливо. Заменил название и поправил импорт.

2023-05-19 14:43 UTC, Yana-Denisova approved these changes

2023-05-22 17:30 UTC, merged