Добавил докстринг
Studio-Yandex-Practicum/rehabilitation_bot pull request #14
Opened 2023-05-15 14:29 UTC by Aleksandr-taxi

тренировка пулреквест

2023-05-15 16:37 UTC, JM1k1 requested changes

2023-05-15 16:37 UTC, JM1k1 commented on src/bot/conversations/main_application.py
>                  context: ContextTypes.DEFAULT_TYPE):
Давай уберем ненужный перенос строки!
```suggestion
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
```
(Ты можешь закоммитить это изменение кнопкой `Commit suggestion`)

2023-05-16 10:08 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
>                  context: ContextTypes.DEFAULT_TYPE):
Пуллреквесту необходимо давать информативное описание и название. А так же в описании необходимо указать номер и название задачи.

2023-05-16 11:20 UTC, Yana-Denisova approved these changes

2023-05-16 11:40 UTC, Yana-Denisova commented
Давай еще поменяем название на fix 3: add docstring to start

2023-05-17 13:24 UTC, JM1k1 approved these changes

2023-05-17 13:26 UTC, merged