Feature/stop command
Studio-Yandex-Practicum/rehabilitation_bot pull request #16
Opened 2023-05-16 05:09 UTC by gazkhul

2023-05-16 09:59 UTC, Yana-Denisova requested changes

2023-05-16 09:59 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
>  async def start(update: Update,
Давай уберем ненужный перенос, так как строка умещается в 79 допустимых символов

2023-05-16 11:03 UTC, gazkhul commented
Изменил и закоммитил здесь, на гитхабе. PR нужен новый?

2023-05-17 09:19 UTC, Yana-Denisova requested changes
Давай название поменяем на feature 10: add stop command

2023-05-18 11:34 UTC, Yana-Denisova approved these changes

2023-05-23 05:33 UTC, merged