Dockerfile и docker-compose.yaml
Studio-Yandex-Practicum/rehabilitation_bot pull request #17
Opened 2023-05-16 10:40 UTC by gazkhul

Добавлен файл сборки контейнера и файл для развертывания инфраструктуры с БД postgresql. Добалены переменные окружения в .env.example

2023-05-23 07:32 UTC, gazkhul commented
В системе оказался poetry версии 1.5.0 и он изменил poetry.lock, поудаляв все строки `category = `. Вернул предыдущий в последнем коммите.

2023-05-23 11:34 UTC, Yana-Denisova requested changes

2023-05-23 11:34 UTC, Yana-Denisova commented on .env.example
> +POSTGRES_USER= # Пользователь по умолчанию postgres
Осталось добавить POSTGRES_PORT

2023-05-25 14:59 UTC, Yana-Denisova approved these changes

2023-05-25 15:31 UTC, merged