перенос настроек линтеров
Studio-Yandex-Practicum/rehabilitation_bot pull request #19
Opened 2023-05-17 07:24 UTC by gazkhul

Настройки `isort` и `flake8` перехали из `setup.cfg` в `pyproject.toml`, файл `setup.cfg` удален из репозитория.
Вместо использования дополнительного аргумента (п. 9) в хук `flake8` добавлена доп. зависимость.

fix 4: Перенести и обновить настройки форматирования

2023-05-17 11:01 UTC, JM1k1 requested changes

2023-05-17 11:24 UTC, Yana-Denisova requested changes

2023-05-17 11:24 UTC, Yana-Denisova commented on .pre-commit-config.yaml
>        args: [--config, setup.cfg]
Мы удалили setup.cfg

2023-05-19 11:16 UTC, Yana-Denisova approved these changes

2023-05-22 17:32 UTC, merged