feature 9: add rehabilitation_bot.yml
Studio-Yandex-Practicum/rehabilitation_bot pull request #24
Opened 2023-05-30 08:53 UTC by Lexxar91

Добавлена папка .github/workflows c файлом rehabilitation_bot.yml, где описывается воркфлоу.
Так же добавлены файлы docker-compose.yml и Dockerfile.

2023-05-30 13:43 UTC, Yana-Denisova requested changes

2023-05-30 13:43 UTC, Yana-Denisova commented on infra/docker-compose.yml
> +version: '3'
Нужно оставить Dockerfile и docker-compose.yml которые сейчас в мастере

2023-06-02 20:14 UTC, Yana-Denisova requested changes

2023-06-02 20:14 UTC, Yana-Denisova commented on infra/Dockerfile
> +CMD ["python", "application.py"]
Нет новой строке в конце файла

2023-06-02 20:14 UTC, Yana-Denisova commented on infra/docker-compose.yaml
> +  postgres_data:
Нет новой строке в конце файла

2023-06-04 06:48 UTC, gazkhul commented on .github/workflows/rehabilitation_bot.yml
> +      - master
Привет! В задаче написано при пуше в release.

2023-06-04 06:50 UTC, gazkhul commented on .github/workflows/rehabilitation_bot.yml
> +        uses: actions/checkout@v2
актуальная v3

2023-06-04 06:50 UTC, gazkhul commented on .github/workflows/rehabilitation_bot.yml
> +        uses: actions/setup-python@v2
актуальная v4

2023-06-06 13:42 UTC, Yana-Denisova approved these changes

2023-06-09 16:14 UTC, merged