research 1: message filtering solution
Studio-Yandex-Practicum/rehabilitation_bot pull request #25
Opened 2023-05-30 10:26 UTC by gazkhul

2023-06-01 06:34 UTC, gazkhul commented
Нужно добавить зависимости.

2023-06-01 16:21 UTC, Yana-Denisova requested changes

2023-06-01 16:21 UTC, Yana-Denisova commented on src/bot/conversations/moderation_application.py
> +# Подготовка данных
Коментарии и докстринг на англ

2023-06-01 16:21 UTC, Yana-Denisova commented on src/bot/core/db/models.py
> +engine = create_engine('sqlite:///sqlite3.db')
Доставайте из сеттингз

2023-06-01 16:21 UTC, Yana-Denisova commented on src/bot/utils.py
> +    msg["From"] = settings.smtp_server_bot_email
Ребят, почему тут изменили кавычки?

2023-06-01 16:21 UTC, Yana-Denisova commented on src/bot/conversations/moderation_application.py
> +forbidden_words = json.load(open('src/bot/forbidden_words.json'))
замените чтение json на чтение списка из базы

2023-06-02 06:23 UTC, gazkhul commented on src/bot/utils.py
> +    msg["From"] = settings.smtp_server_bot_email
Видимо, моя вина. Включил format on save, он меняет кавычки. Включал смело, т.к. в кодстайле написано, что используем двойные.

2023-06-12 15:59 UTC, Yana-Denisova requested changes

2023-06-12 15:59 UTC, Yana-Denisova commented on alembic/README
> +Generic single-database configuration with an async dbapi.
ридми у алембик можно убрать

2023-06-12 15:59 UTC, Yana-Denisova commented on src/bot/constants/key.py
> -ASK = "ASK"
необходимо вернуть аск

2023-06-12 15:59 UTC, Yana-Denisova commented on src/bot/constants/state.py
> -) = range(3)
Стейты необходимы для хендлера форм

2023-06-12 16:00 UTC, Yana-Denisova commented
Ребята, скорее всего вы неправильно замерджили из мастера на каком-то этапе, поэтому у вас в пуллреквесте отлетели новые изменения (логгер, хендлер анкеты, файл анкеты и тд)

2023-06-20 15:47 UTC, gazkhul commented
Забыл про кавычки. Отдельным коммитом верну.

2023-06-24 14:30 UTC, JM1k1 requested changes
Мы обновили код в мастере, замерджи изменения и разреши конфликты! :)

2023-06-24 14:35 UTC, Yana-Denisova requested changes
В мастере появилось  много изменений, потяни актуальную версию кода из мастер в свою ветку и интегрируй туда свой код. Если этого не сделать на этом этапе, то он может не заработать и будут конфликты. После этого обязательно протестируй и удостоверься что код работает. :)

2023-06-28 19:34 UTC, JM1k1 approved these changes

2023-06-28 19:34 UTC, JM1k1 commented on src/bot/core/settings.py
> +    chat_id: int
Этот атрибут где-нибудь используется?

2023-06-28 19:34 UTC, JM1k1 commented on src/bot/core/db/alembic/versions/a44e81df0712_clr_history.py
> +"""clr history
У нас пока что не релиз, так что давай оставим одну версию. (Создай новую, старые можешь удалить)

2023-06-30 07:27 UTC, gazkhul commented on src/bot/core/settings.py
> +    chat_id: int
Убрал. Осталось от ручного заполнения бд.

2023-07-13 16:11 UTC, merged