feature 16/add logging
Studio-Yandex-Practicum/rehabilitation_bot pull request #26
Opened 2023-06-01 09:06 UTC by ArtyKurkin

Добавлен конфигурационный файл логирования из словаря в **src/bot/core/logger.py**.
В **src/bot/core/settings.py** добавлены формат, путь и уровень логирования.
В **src/application.py** добавлен импорт логера `from bot.core import logger  # noqa`.
_feature 16: Добавить конфигурационный файл логирования._

2023-06-01 16:09 UTC, Yana-Denisova requested changes

2023-06-01 16:09 UTC, Yana-Denisova commented on src/bot/core/logger.py
> +            'filename': LOG_PATH / settings.log_filename,
Давай LOG_PATH в константы вынесем на 9 строчку

2023-06-04 14:15 UTC, Yana-Denisova approved these changes

2023-06-04 14:16 UTC, JM1k1 approved these changes

2023-06-05 06:55 UTC, merged