create base handler
Studio-Yandex-Practicum/rehabilitation_bot pull request #7
Opened 2023-04-27 11:28 UTC by SolovyevAlexey

2023-04-28 16:30 UTC, Yana-Denisova requested changes

2023-04-28 16:30 UTC, Yana-Denisova commented on src/application.py
> +async def start(update: Update,
Давай перенесем эту функцию в src\bot\conversations\main_application.py

2023-04-28 16:39 UTC, JM1k1 approved these changes

2023-04-28 16:39 UTC, JM1k1 commented on src/bot/constants/info/text.py
> +MESSAGE = 'Здесь должно быть приветственное сообщение (Заглушка)!'
Название константы должно быть информативным.
```suggestion
START_MESSAGE = 'Здесь должно быть приветственное сообщение (Заглушка)!'
```

2023-04-29 12:19 UTC, JM1k1 requested changes

2023-04-29 12:19 UTC, JM1k1 commented on src/application.py
> +    application = Application.builder().token(Settings.telegram_token).build()
При использовании pydantic settings manager необходимо импортировать экземпляр класса Settings, а не сам класс.

[Рекомендую ознакомиться с документацией :)](https://docs.pydantic.dev/latest/usage/settings/)

2023-04-29 12:43 UTC, JM1k1 approved these changes

2023-04-29 16:53 UTC, Yana-Denisova approved these changes

2023-04-30 01:14 UTC, merged